package air.deterministic_policy_test

import rego.v1
import data.air.deterministic_policy

test_ws5reg_allow_01 if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"PROMPT_SIMULATED","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"READ_ONLY","effect_level":"READ_ONLY","environment":"LOCAL","resource_classes":["local_file"],"approval_required":false,"approval_present":false,"binding_requested":false,"validation_state":"NOT_REQUIRED","repository_action":false,"release_action":false,"dependency_state":{"mandatory_external_engine":false,"mandatory_hosted_service":false,"mandatory_package_manager":false},"taxonomy_binding_state":"TRANSLATED_OR_NOT_APPLICABLE","human_status_transfer_state":"NONE","claim_state":{},"evidence_state":{},"unknown_fields":[],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"policy_posture":"MEDIUM","material_transition":false,"tool_configured":false,"tool_available":false,"tool_authorized":false,"tool_invoked":false,"tool_endpoint":"LOCAL_CLI"}
  result.decision == "ALLOW"
}

test_ws5reg_approval_r_01 if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"PROMPT_SIMULATED","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"GENERATE","effect_level":"WRITE","environment":"LOCAL","resource_classes":["local_file"],"approval_required":true,"approval_present":false,"binding_requested":false,"validation_state":"NOT_REQUIRED","repository_action":false,"release_action":false,"dependency_state":{"mandatory_external_engine":false,"mandatory_hosted_service":false,"mandatory_package_manager":false},"taxonomy_binding_state":"TRANSLATED_OR_NOT_APPLICABLE","human_status_transfer_state":"NONE","claim_state":{},"evidence_state":{},"unknown_fields":[],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"policy_posture":"MEDIUM","material_transition":true,"tool_configured":false,"tool_available":false,"tool_authorized":false,"tool_invoked":false,"tool_endpoint":"LOCAL_CLI"}
  result.decision == "REJECT"
}

test_ws5reg_approval_a_01 if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"PROMPT_SIMULATED","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"GENERATE","effect_level":"WRITE","environment":"LOCAL","resource_classes":["local_file"],"approval_required":true,"approval_present":true,"binding_requested":false,"validation_state":"NOT_REQUIRED","repository_action":false,"release_action":false,"dependency_state":{"mandatory_external_engine":false,"mandatory_hosted_service":false,"mandatory_package_manager":false},"taxonomy_binding_state":"TRANSLATED_OR_NOT_APPLICABLE","human_status_transfer_state":"NONE","claim_state":{},"evidence_state":{},"unknown_fields":[],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"policy_posture":"MEDIUM","material_transition":true,"tool_configured":false,"tool_available":false,"tool_authorized":false,"tool_invoked":false,"tool_endpoint":"LOCAL_CLI"}
  result.decision == "ALLOW"
}

test_ws5reg_bind_r_01 if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"PROMPT_SIMULATED","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"BIND","effect_level":"WRITE","environment":"LOCAL","resource_classes":["local_file"],"approval_required":true,"approval_present":true,"binding_requested":true,"validation_state":"FAIL","repository_action":false,"release_action":false,"dependency_state":{"mandatory_external_engine":false,"mandatory_hosted_service":false,"mandatory_package_manager":false},"taxonomy_binding_state":"TRANSLATED_OR_NOT_APPLICABLE","human_status_transfer_state":"NONE","claim_state":{},"evidence_state":{},"unknown_fields":[],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"binding_approval_present":true,"policy_posture":"MEDIUM","material_transition":true,"tool_configured":false,"tool_available":false,"tool_authorized":false,"tool_invoked":false,"tool_endpoint":"LOCAL_CLI"}
  result.decision == "REJECT"
}

test_ws5reg_bind_a_01 if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"PROMPT_SIMULATED","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"BIND","effect_level":"WRITE","environment":"LOCAL","resource_classes":["local_file"],"approval_required":true,"approval_present":true,"binding_requested":true,"validation_state":"PASS","repository_action":false,"release_action":false,"dependency_state":{"mandatory_external_engine":false,"mandatory_hosted_service":false,"mandatory_package_manager":false},"taxonomy_binding_state":"TRANSLATED_OR_NOT_APPLICABLE","human_status_transfer_state":"NONE","claim_state":{},"evidence_state":{},"unknown_fields":[],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"binding_approval_present":true,"policy_posture":"MEDIUM","material_transition":true,"tool_configured":false,"tool_available":false,"tool_authorized":false,"tool_invoked":false,"tool_endpoint":"LOCAL_CLI"}
  result.decision == "ALLOW"
}

test_ws5reg_repo_r_01 if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"PROMPT_SIMULATED","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"REPOSITORY","effect_level":"WRITE","environment":"LOCAL","resource_classes":["local_file"],"approval_required":true,"approval_present":true,"binding_requested":false,"validation_state":"NOT_REQUIRED","repository_action":true,"release_action":false,"dependency_state":{"mandatory_external_engine":false,"mandatory_hosted_service":false,"mandatory_package_manager":false},"taxonomy_binding_state":"TRANSLATED_OR_NOT_APPLICABLE","human_status_transfer_state":"NONE","claim_state":{},"evidence_state":{},"unknown_fields":[],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"policy_posture":"MEDIUM","material_transition":true,"tool_configured":false,"tool_available":false,"tool_authorized":false,"tool_invoked":false,"tool_endpoint":"LOCAL_CLI"}
  result.decision == "REJECT"
}

test_ws5reg_repo_a_01 if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"PROMPT_SIMULATED","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"REPOSITORY","effect_level":"WRITE","environment":"LOCAL","resource_classes":["local_file"],"approval_required":true,"approval_present":true,"binding_requested":false,"validation_state":"NOT_REQUIRED","repository_action":true,"release_action":false,"dependency_state":{"mandatory_external_engine":false,"mandatory_hosted_service":false,"mandatory_package_manager":false},"taxonomy_binding_state":"TRANSLATED_OR_NOT_APPLICABLE","human_status_transfer_state":"NONE","claim_state":{},"evidence_state":{},"unknown_fields":[],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"repository_approval_present":true,"policy_posture":"MEDIUM","material_transition":true,"tool_configured":false,"tool_available":false,"tool_authorized":false,"tool_invoked":false,"tool_endpoint":"LOCAL_CLI"}
  result.decision == "ALLOW"
}

test_ws5reg_dep_r_01 if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"PROMPT_SIMULATED","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"READ_ONLY","effect_level":"READ_ONLY","environment":"LOCAL","resource_classes":["local_file"],"approval_required":false,"approval_present":false,"binding_requested":false,"validation_state":"NOT_REQUIRED","repository_action":false,"release_action":false,"dependency_state":{"mandatory_external_engine":true,"mandatory_hosted_service":false,"mandatory_package_manager":false},"taxonomy_binding_state":"TRANSLATED_OR_NOT_APPLICABLE","human_status_transfer_state":"NONE","claim_state":{},"evidence_state":{},"unknown_fields":[],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"policy_posture":"MEDIUM","material_transition":false,"tool_configured":false,"tool_available":false,"tool_authorized":false,"tool_invoked":false,"tool_endpoint":"LOCAL_CLI"}
  result.decision == "REJECT"
}

test_ws5reg_dep_a_01 if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"PROMPT_SIMULATED","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"READ_ONLY","effect_level":"READ_ONLY","environment":"LOCAL","resource_classes":["local_file"],"approval_required":false,"approval_present":false,"binding_requested":false,"validation_state":"NOT_REQUIRED","repository_action":false,"release_action":false,"dependency_state":{"mandatory_external_engine":false,"mandatory_hosted_service":false,"mandatory_package_manager":false},"taxonomy_binding_state":"TRANSLATED_OR_NOT_APPLICABLE","human_status_transfer_state":"NONE","claim_state":{},"evidence_state":{},"unknown_fields":[],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"policy_posture":"MEDIUM","material_transition":false,"tool_configured":false,"tool_available":false,"tool_authorized":false,"tool_invoked":false,"tool_endpoint":"LOCAL_CLI"}
  result.decision == "ALLOW"
}

test_ws5reg_tax_r_01 if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"PROMPT_SIMULATED","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"READ_ONLY","effect_level":"READ_ONLY","environment":"LOCAL","resource_classes":["local_file"],"approval_required":false,"approval_present":false,"binding_requested":false,"validation_state":"NOT_REQUIRED","repository_action":false,"release_action":false,"dependency_state":{"mandatory_external_engine":false,"mandatory_hosted_service":false,"mandatory_package_manager":false},"taxonomy_binding_state":"RAW_DIRECT_BINDING","human_status_transfer_state":"NONE","claim_state":{},"evidence_state":{},"unknown_fields":[],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"policy_posture":"MEDIUM","material_transition":false,"tool_configured":false,"tool_available":false,"tool_authorized":false,"tool_invoked":false,"tool_endpoint":"LOCAL_CLI"}
  result.decision == "REJECT"
}

test_ws5reg_human_a_01 if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"PROMPT_SIMULATED","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"READ_ONLY","effect_level":"READ_ONLY","environment":"LOCAL","resource_classes":["local_file"],"approval_required":false,"approval_present":false,"binding_requested":false,"validation_state":"NOT_REQUIRED","repository_action":false,"release_action":false,"dependency_state":{"mandatory_external_engine":false,"mandatory_hosted_service":false,"mandatory_package_manager":false},"taxonomy_binding_state":"TRANSLATED_OR_NOT_APPLICABLE","human_status_transfer_state":"NONE","claim_state":{},"evidence_state":{},"unknown_fields":[],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"policy_posture":"MEDIUM","material_transition":false,"tool_configured":false,"tool_available":false,"tool_authorized":false,"tool_invoked":false,"tool_endpoint":"LOCAL_CLI"}
  result.decision == "ALLOW"
}

test_ws5reg_claim_r_01 if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"PROMPT_SIMULATED","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"READ_ONLY","effect_level":"READ_ONLY","environment":"LOCAL","resource_classes":["local_file"],"approval_required":false,"approval_present":false,"binding_requested":false,"validation_state":"NOT_REQUIRED","repository_action":false,"release_action":false,"dependency_state":{"mandatory_external_engine":false,"mandatory_hosted_service":false,"mandatory_package_manager":false},"taxonomy_binding_state":"TRANSLATED_OR_NOT_APPLICABLE","human_status_transfer_state":"NONE","claim_state":{"backend_enforced":true},"evidence_state":{},"unknown_fields":[],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"policy_posture":"MEDIUM","material_transition":false,"tool_configured":false,"tool_available":false,"tool_authorized":false,"tool_invoked":false,"tool_endpoint":"LOCAL_CLI"}
  result.decision == "REJECT"
}

test_ws5reg_claim_a_04 if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"PROMPT_SIMULATED","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"READ_ONLY","effect_level":"READ_ONLY","environment":"LOCAL","resource_classes":["local_file"],"approval_required":false,"approval_present":false,"binding_requested":false,"validation_state":"NOT_REQUIRED","repository_action":false,"release_action":false,"dependency_state":{"mandatory_external_engine":false,"mandatory_hosted_service":false,"mandatory_package_manager":false},"taxonomy_binding_state":"TRANSLATED_OR_NOT_APPLICABLE","human_status_transfer_state":"NONE","claim_state":{"release_ready":true},"evidence_state":{"release_evidence":true},"unknown_fields":[],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"policy_posture":"MEDIUM","material_transition":false,"tool_configured":false,"tool_available":false,"tool_authorized":false,"tool_invoked":false,"tool_endpoint":"LOCAL_CLI"}
  result.decision == "ALLOW"
}

test_ws5reg_mode_e_01 if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"PROMPT_SIMULATED","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"READ_ONLY","effect_level":"READ_ONLY","environment":"LOCAL","resource_classes":["local_file"],"approval_required":false,"approval_present":false,"binding_requested":false,"validation_state":"NOT_REQUIRED","repository_action":false,"release_action":false,"dependency_state":{"mandatory_external_engine":false,"mandatory_hosted_service":false,"mandatory_package_manager":false},"taxonomy_binding_state":"TRANSLATED_OR_NOT_APPLICABLE","human_status_transfer_state":"NONE","claim_state":{},"evidence_state":{},"unknown_fields":[],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"_malformed":true,"policy_posture":"MEDIUM","material_transition":false,"tool_configured":false,"tool_available":false,"tool_authorized":false,"tool_invoked":false,"tool_endpoint":"LOCAL_CLI"}
  result.decision == "ALLOW"
}

test_ws5reg_mode_e_02 if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"PROMPT_SIMULATED","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"READ_ONLY","effect_level":"READ_ONLY","environment":"LOCAL","resource_classes":["local_file"],"approval_required":false,"approval_present":false,"binding_requested":false,"validation_state":"NOT_REQUIRED","repository_action":false,"release_action":false,"dependency_state":{"mandatory_external_engine":false,"mandatory_hosted_service":false,"mandatory_package_manager":false},"taxonomy_binding_state":"TRANSLATED_OR_NOT_APPLICABLE","human_status_transfer_state":"NONE","claim_state":{},"evidence_state":{},"unknown_fields":[],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"engine_error":"PARSE_ERROR","policy_posture":"MEDIUM","material_transition":false,"tool_configured":false,"tool_available":false,"tool_authorized":false,"tool_invoked":false,"tool_endpoint":"LOCAL_CLI"}
  result.decision == "ERROR"
}

test_ws5reg_mode_q_01 if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"PROMPT_SIMULATED","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"READ_ONLY","effect_level":"READ_ONLY","environment":"LOCAL","resource_classes":["local_file"],"approval_required":false,"approval_present":false,"binding_requested":false,"validation_state":"NOT_REQUIRED","repository_action":false,"release_action":false,"dependency_state":{"mandatory_external_engine":false,"mandatory_hosted_service":false,"mandatory_package_manager":false},"taxonomy_binding_state":"TRANSLATED_OR_NOT_APPLICABLE","human_status_transfer_state":"NONE","claim_state":{},"evidence_state":{},"unknown_fields":[],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"undefined_result":true,"policy_posture":"MEDIUM","material_transition":false,"tool_configured":false,"tool_available":false,"tool_authorized":false,"tool_invoked":false,"tool_endpoint":"LOCAL_CLI"}
  result.decision == "EVIDENCE_REQUIRED"
}

test_ws5reg_mode_rv_01 if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"PROMPT_SIMULATED","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"READ_ONLY","effect_level":"READ_ONLY","environment":"LOCAL","resource_classes":["local_file"],"approval_required":false,"approval_present":false,"binding_requested":false,"validation_state":"NOT_REQUIRED","repository_action":false,"release_action":false,"dependency_state":{"mandatory_external_engine":false,"mandatory_hosted_service":false,"mandatory_package_manager":false},"taxonomy_binding_state":"TRANSLATED_OR_NOT_APPLICABLE","human_status_transfer_state":"NONE","claim_state":{},"evidence_state":{},"unknown_fields":[],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"policy_version_mismatch":true,"policy_posture":"MEDIUM","material_transition":false,"tool_configured":false,"tool_available":false,"tool_authorized":false,"tool_invoked":false,"tool_endpoint":"LOCAL_CLI"}
  result.decision == "REVIEW"
}

test_ws5reg_mode_r_01 if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"PROMPT_SIMULATED","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"READ_ONLY","effect_level":"READ_ONLY","environment":"LOCAL","resource_classes":["local_file"],"approval_required":false,"approval_present":false,"binding_requested":false,"validation_state":"NOT_REQUIRED","repository_action":false,"release_action":false,"dependency_state":{"mandatory_external_engine":false,"mandatory_hosted_service":false,"mandatory_package_manager":false},"taxonomy_binding_state":"TRANSLATED_OR_NOT_APPLICABLE","human_status_transfer_state":"NONE","claim_state":{"tool_evaluated":true},"evidence_state":{},"unknown_fields":[],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"policy_posture":"MEDIUM","material_transition":false,"tool_configured":false,"tool_available":false,"tool_authorized":false,"tool_invoked":false,"tool_endpoint":"LOCAL_CLI"}
  result.decision == "REJECT"
}

test_ws5reg_unknown_rv_01 if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"PROMPT_SIMULATED","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"UNKNOWN","effect_level":"UNKNOWN","environment":"LOCAL","resource_classes":["local_file"],"approval_required":false,"approval_present":false,"binding_requested":false,"validation_state":"NOT_REQUIRED","repository_action":false,"release_action":false,"dependency_state":{"mandatory_external_engine":false,"mandatory_hosted_service":false,"mandatory_package_manager":false},"taxonomy_binding_state":"TRANSLATED_OR_NOT_APPLICABLE","human_status_transfer_state":"NONE","claim_state":{},"evidence_state":{},"unknown_fields":[],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"policy_posture":"MEDIUM","material_transition":false,"tool_configured":false,"tool_available":false,"tool_authorized":false,"tool_invoked":false,"tool_endpoint":"LOCAL_CLI"}
  result.decision == "REVIEW"
}

test_ws5reg_unknown_e_01 if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"PROMPT_SIMULATED","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"MUTATE","effect_level":"WRITE","environment":"LOCAL","resource_classes":["local_file"],"approval_required":true,"approval_present":true,"binding_requested":false,"validation_state":"NOT_REQUIRED","repository_action":false,"release_action":false,"dependency_state":{"mandatory_external_engine":false,"mandatory_hosted_service":false,"mandatory_package_manager":false},"taxonomy_binding_state":"TRANSLATED_OR_NOT_APPLICABLE","human_status_transfer_state":"NONE","claim_state":{},"evidence_state":{},"unknown_fields":["unresolved_context"],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"policy_posture":"MEDIUM","material_transition":true,"tool_configured":false,"tool_available":false,"tool_authorized":false,"tool_invoked":false,"tool_endpoint":"LOCAL_CLI"}
  result.decision == "EVIDENCE_REQUIRED"
}

test_ws5reg_unknown_a_01 if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"PROMPT_SIMULATED","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"READ_ONLY","effect_level":"READ_ONLY","environment":"LOCAL","resource_classes":["local_file"],"approval_required":false,"approval_present":false,"binding_requested":false,"validation_state":"NOT_REQUIRED","repository_action":false,"release_action":false,"dependency_state":{"mandatory_external_engine":false,"mandatory_hosted_service":false,"mandatory_package_manager":false},"taxonomy_binding_state":"TRANSLATED_OR_NOT_APPLICABLE","human_status_transfer_state":"NONE","claim_state":{},"evidence_state":{},"unknown_fields":[],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"policy_posture":"MEDIUM","material_transition":false,"tool_configured":false,"tool_available":false,"tool_authorized":false,"tool_invoked":false,"tool_endpoint":"LOCAL_CLI"}
  result.decision == "ALLOW"
}

test_q2_low_0_000 if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"PROMPT_SIMULATED","policy_posture":"LOW","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"READ_ONLY","effect_level":"READ_ONLY","environment":"LOCAL","resource_classes":["local_file"],"approval_required":false,"approval_present":false,"binding_requested":false,"validation_state":"NOT_REQUIRED","repository_action":false,"release_action":false,"dependency_state":{"mandatory_external_engine":false,"mandatory_hosted_service":false,"mandatory_package_manager":false,"mandatory_network":false,"mandatory_central_service":false},"taxonomy_binding_state":"TRANSLATED_OR_NOT_APPLICABLE","human_status_transfer_state":"NONE","claim_state":{},"evidence_state":{},"unknown_fields":[],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"material_transition":false,"tool_configured":false,"tool_available":false,"tool_authorized":false,"tool_invoked":false,"tool_endpoint":"LOCAL_CLI"}
  result.decision == "ALLOW"
}

test_endpoint_local_cli if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"PROMPT_SIMULATED","policy_posture":"MEDIUM","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"READ_ONLY","effect_level":"READ_ONLY","environment":"LOCAL","resource_classes":["local_file"],"approval_required":false,"approval_present":false,"binding_requested":false,"validation_state":"NOT_REQUIRED","repository_action":false,"release_action":false,"dependency_state":{"mandatory_external_engine":false,"mandatory_hosted_service":false,"mandatory_package_manager":false,"mandatory_network":false,"mandatory_central_service":false},"taxonomy_binding_state":"TRANSLATED_OR_NOT_APPLICABLE","human_status_transfer_state":"NONE","claim_state":{},"evidence_state":{},"unknown_fields":[],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"material_transition":false,"tool_configured":true,"tool_available":true,"tool_authorized":true,"tool_invoked":false,"tool_endpoint":"LOCAL_CLI"}
  result.decision == "ALLOW"
}

test_endpoint_0_0_0_0_8181 if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"PROMPT_SIMULATED","policy_posture":"MEDIUM","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"READ_ONLY","effect_level":"READ_ONLY","environment":"LOCAL","resource_classes":["local_file"],"approval_required":false,"approval_present":false,"binding_requested":false,"validation_state":"NOT_REQUIRED","repository_action":false,"release_action":false,"dependency_state":{"mandatory_external_engine":false,"mandatory_hosted_service":false,"mandatory_package_manager":false,"mandatory_network":false,"mandatory_central_service":false},"taxonomy_binding_state":"TRANSLATED_OR_NOT_APPLICABLE","human_status_transfer_state":"NONE","claim_state":{},"evidence_state":{},"unknown_fields":[],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"material_transition":false,"tool_configured":true,"tool_available":true,"tool_authorized":true,"tool_invoked":false,"tool_endpoint":"0.0.0.0:8181"}
  result.decision == "REJECT"
}

test_err_parse_error if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"TOOL_EVALUATED","policy_posture":"MEDIUM","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"READ_ONLY","effect_level":"READ_ONLY","environment":"LOCAL","resource_classes":["local_file"],"approval_required":false,"approval_present":false,"binding_requested":false,"validation_state":"NOT_REQUIRED","repository_action":false,"release_action":false,"dependency_state":{"mandatory_external_engine":false,"mandatory_hosted_service":false,"mandatory_package_manager":false,"mandatory_network":false,"mandatory_central_service":false},"taxonomy_binding_state":"TRANSLATED_OR_NOT_APPLICABLE","human_status_transfer_state":"NONE","claim_state":{},"evidence_state":{},"unknown_fields":[],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"material_transition":false,"tool_configured":true,"tool_available":true,"tool_authorized":true,"tool_invoked":true,"tool_endpoint":"LOCAL_CLI","tool_provenance_present":true,"engine_error":"PARSE_ERROR"}
  result.decision == "ERROR"
}

test_fail_undefined_result if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"PROMPT_SIMULATED","policy_posture":"MEDIUM","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"READ_ONLY","effect_level":"READ_ONLY","environment":"LOCAL","resource_classes":["local_file"],"approval_required":false,"approval_present":false,"binding_requested":false,"validation_state":"NOT_REQUIRED","repository_action":false,"release_action":false,"dependency_state":{"mandatory_external_engine":false,"mandatory_hosted_service":false,"mandatory_package_manager":false,"mandatory_network":false,"mandatory_central_service":false},"taxonomy_binding_state":"TRANSLATED_OR_NOT_APPLICABLE","human_status_transfer_state":"NONE","claim_state":{},"evidence_state":{},"unknown_fields":[],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"material_transition":false,"tool_configured":false,"tool_available":false,"tool_authorized":false,"tool_invoked":false,"tool_endpoint":"LOCAL_CLI","undefined_result":true}
  result.decision == "EVIDENCE_REQUIRED"
}

test_fail_policy_version_mismatch if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"PROMPT_SIMULATED","policy_posture":"MEDIUM","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"READ_ONLY","effect_level":"READ_ONLY","environment":"LOCAL","resource_classes":["local_file"],"approval_required":false,"approval_present":false,"binding_requested":false,"validation_state":"NOT_REQUIRED","repository_action":false,"release_action":false,"dependency_state":{"mandatory_external_engine":false,"mandatory_hosted_service":false,"mandatory_package_manager":false,"mandatory_network":false,"mandatory_central_service":false},"taxonomy_binding_state":"TRANSLATED_OR_NOT_APPLICABLE","human_status_transfer_state":"NONE","claim_state":{},"evidence_state":{},"unknown_fields":[],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"material_transition":false,"tool_configured":false,"tool_available":false,"tool_authorized":false,"tool_invoked":false,"tool_endpoint":"LOCAL_CLI","policy_version_mismatch":true}
  result.decision == "REVIEW"
}

test_fail_runtime_conflict if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"PROMPT_SIMULATED","policy_posture":"MEDIUM","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"READ_ONLY","effect_level":"READ_ONLY","environment":"LOCAL","resource_classes":["local_file"],"approval_required":false,"approval_present":false,"binding_requested":false,"validation_state":"NOT_REQUIRED","repository_action":false,"release_action":false,"dependency_state":{"mandatory_external_engine":false,"mandatory_hosted_service":false,"mandatory_package_manager":false,"mandatory_network":false,"mandatory_central_service":false},"taxonomy_binding_state":"TRANSLATED_OR_NOT_APPLICABLE","human_status_transfer_state":"NONE","claim_state":{},"evidence_state":{},"unknown_fields":[],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"material_transition":false,"tool_configured":false,"tool_available":false,"tool_authorized":false,"tool_invoked":false,"tool_endpoint":"LOCAL_CLI","runtime_conflict":true}
  result.decision == "REJECT"
}

test_approval_missing_generate if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"PROMPT_SIMULATED","policy_posture":"MEDIUM","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"GENERATE","effect_level":"WRITE","environment":"LOCAL","resource_classes":["local_file"],"approval_required":true,"approval_present":false,"binding_requested":false,"validation_state":"NOT_REQUIRED","repository_action":false,"release_action":false,"dependency_state":{"mandatory_external_engine":false,"mandatory_hosted_service":false,"mandatory_package_manager":false,"mandatory_network":false,"mandatory_central_service":false},"taxonomy_binding_state":"TRANSLATED_OR_NOT_APPLICABLE","human_status_transfer_state":"NONE","claim_state":{},"evidence_state":{},"unknown_fields":[],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"material_transition":true,"tool_configured":false,"tool_available":false,"tool_authorized":false,"tool_invoked":false,"tool_endpoint":"LOCAL_CLI"}
  result.decision == "REJECT"
}

test_approval_present_generate if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"PROMPT_SIMULATED","policy_posture":"MEDIUM","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"GENERATE","effect_level":"WRITE","environment":"LOCAL","resource_classes":["local_file"],"approval_required":true,"approval_present":true,"binding_requested":false,"validation_state":"NOT_REQUIRED","repository_action":false,"release_action":false,"dependency_state":{"mandatory_external_engine":false,"mandatory_hosted_service":false,"mandatory_package_manager":false,"mandatory_network":false,"mandatory_central_service":false},"taxonomy_binding_state":"TRANSLATED_OR_NOT_APPLICABLE","human_status_transfer_state":"NONE","claim_state":{},"evidence_state":{},"unknown_fields":[],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"material_transition":true,"tool_configured":false,"tool_available":false,"tool_authorized":false,"tool_invoked":false,"tool_endpoint":"LOCAL_CLI","repository_approval_present":false,"release_approval_present":false}
  result.decision == "ALLOW"
}

test_claim_missing_backend_enforced if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"PROMPT_SIMULATED","policy_posture":"MEDIUM","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"READ_ONLY","effect_level":"READ_ONLY","environment":"LOCAL","resource_classes":["local_file"],"approval_required":false,"approval_present":false,"binding_requested":false,"validation_state":"NOT_REQUIRED","repository_action":false,"release_action":false,"dependency_state":{"mandatory_external_engine":false,"mandatory_hosted_service":false,"mandatory_package_manager":false,"mandatory_network":false,"mandatory_central_service":false},"taxonomy_binding_state":"TRANSLATED_OR_NOT_APPLICABLE","human_status_transfer_state":"NONE","claim_state":{"backend_enforced":true},"evidence_state":{},"unknown_fields":[],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"material_transition":false,"tool_configured":false,"tool_available":false,"tool_authorized":false,"tool_invoked":false,"tool_endpoint":"LOCAL_CLI"}
  result.decision == "REJECT"
}

test_claim_present_backend_enforced if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"PROMPT_SIMULATED","policy_posture":"MEDIUM","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"READ_ONLY","effect_level":"READ_ONLY","environment":"LOCAL","resource_classes":["local_file"],"approval_required":false,"approval_present":false,"binding_requested":false,"validation_state":"NOT_REQUIRED","repository_action":false,"release_action":false,"dependency_state":{"mandatory_external_engine":false,"mandatory_hosted_service":false,"mandatory_package_manager":false,"mandatory_network":false,"mandatory_central_service":false},"taxonomy_binding_state":"TRANSLATED_OR_NOT_APPLICABLE","human_status_transfer_state":"NONE","claim_state":{"backend_enforced":true},"evidence_state":{"backend_enforced":true},"unknown_fields":[],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"material_transition":false,"tool_configured":false,"tool_available":false,"tool_authorized":false,"tool_invoked":false,"tool_endpoint":"LOCAL_CLI"}
  result.decision == "ALLOW"
}

test_q2_low_0_000 if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"PROMPT_SIMULATED","policy_posture":"LOW","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"READ_ONLY","effect_level":"READ_ONLY","environment":"LOCAL","resource_classes":["local_file"],"approval_required":false,"approval_present":false,"binding_requested":false,"validation_state":"NOT_REQUIRED","repository_action":false,"release_action":false,"dependency_state":{"mandatory_external_engine":false,"mandatory_hosted_service":false,"mandatory_package_manager":false,"mandatory_network":false,"mandatory_central_service":false},"taxonomy_binding_state":"TRANSLATED_OR_NOT_APPLICABLE","human_status_transfer_state":"NONE","claim_state":{},"evidence_state":{},"unknown_fields":[],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"material_transition":false,"tool_configured":false,"tool_available":false,"tool_authorized":false,"tool_invoked":false,"tool_endpoint":"LOCAL_CLI"}
  result.decision == "ALLOW"
}

test_q2_low_0_101 if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"PROMPT_SIMULATED","policy_posture":"LOW","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"READ_ONLY","effect_level":"READ_ONLY","environment":"LOCAL","resource_classes":["local_file"],"approval_required":false,"approval_present":false,"binding_requested":false,"validation_state":"NOT_REQUIRED","repository_action":false,"release_action":false,"dependency_state":{"mandatory_external_engine":false,"mandatory_hosted_service":false,"mandatory_package_manager":false,"mandatory_network":false,"mandatory_central_service":false},"taxonomy_binding_state":"TRANSLATED_OR_NOT_APPLICABLE","human_status_transfer_state":"NONE","claim_state":{},"evidence_state":{},"unknown_fields":[],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"material_transition":false,"tool_configured":true,"tool_available":false,"tool_authorized":true,"tool_invoked":false,"tool_endpoint":"LOCAL_CLI"}
  result.decision == "ALLOW"
}

test_q2_low_0_110 if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"PROMPT_SIMULATED","policy_posture":"LOW","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"READ_ONLY","effect_level":"READ_ONLY","environment":"LOCAL","resource_classes":["local_file"],"approval_required":false,"approval_present":false,"binding_requested":false,"validation_state":"NOT_REQUIRED","repository_action":false,"release_action":false,"dependency_state":{"mandatory_external_engine":false,"mandatory_hosted_service":false,"mandatory_package_manager":false,"mandatory_network":false,"mandatory_central_service":false},"taxonomy_binding_state":"TRANSLATED_OR_NOT_APPLICABLE","human_status_transfer_state":"NONE","claim_state":{},"evidence_state":{},"unknown_fields":[],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"material_transition":false,"tool_configured":true,"tool_available":true,"tool_authorized":false,"tool_invoked":false,"tool_endpoint":"LOCAL_CLI"}
  result.decision == "ALLOW"
}

test_q2_low_0_111 if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"PROMPT_SIMULATED","policy_posture":"LOW","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"READ_ONLY","effect_level":"READ_ONLY","environment":"LOCAL","resource_classes":["local_file"],"approval_required":false,"approval_present":false,"binding_requested":false,"validation_state":"NOT_REQUIRED","repository_action":false,"release_action":false,"dependency_state":{"mandatory_external_engine":false,"mandatory_hosted_service":false,"mandatory_package_manager":false,"mandatory_network":false,"mandatory_central_service":false},"taxonomy_binding_state":"TRANSLATED_OR_NOT_APPLICABLE","human_status_transfer_state":"NONE","claim_state":{},"evidence_state":{},"unknown_fields":[],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"material_transition":false,"tool_configured":true,"tool_available":true,"tool_authorized":true,"tool_invoked":false,"tool_endpoint":"LOCAL_CLI"}
  result.decision == "ALLOW"
}

test_q2_low_1_000 if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"PROMPT_SIMULATED","policy_posture":"LOW","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"READ_ONLY","effect_level":"READ_ONLY","environment":"LOCAL","resource_classes":["local_file"],"approval_required":false,"approval_present":false,"binding_requested":false,"validation_state":"NOT_REQUIRED","repository_action":false,"release_action":false,"dependency_state":{"mandatory_external_engine":false,"mandatory_hosted_service":false,"mandatory_package_manager":false,"mandatory_network":false,"mandatory_central_service":false},"taxonomy_binding_state":"TRANSLATED_OR_NOT_APPLICABLE","human_status_transfer_state":"NONE","claim_state":{},"evidence_state":{},"unknown_fields":[],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"material_transition":true,"tool_configured":false,"tool_available":false,"tool_authorized":false,"tool_invoked":false,"tool_endpoint":"LOCAL_CLI"}
  result.decision == "ALLOW"
}

test_q2_low_1_101 if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"PROMPT_SIMULATED","policy_posture":"LOW","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"READ_ONLY","effect_level":"READ_ONLY","environment":"LOCAL","resource_classes":["local_file"],"approval_required":false,"approval_present":false,"binding_requested":false,"validation_state":"NOT_REQUIRED","repository_action":false,"release_action":false,"dependency_state":{"mandatory_external_engine":false,"mandatory_hosted_service":false,"mandatory_package_manager":false,"mandatory_network":false,"mandatory_central_service":false},"taxonomy_binding_state":"TRANSLATED_OR_NOT_APPLICABLE","human_status_transfer_state":"NONE","claim_state":{},"evidence_state":{},"unknown_fields":[],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"material_transition":true,"tool_configured":true,"tool_available":false,"tool_authorized":true,"tool_invoked":false,"tool_endpoint":"LOCAL_CLI"}
  result.decision == "ALLOW"
}

test_q2_low_1_110 if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"PROMPT_SIMULATED","policy_posture":"LOW","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"READ_ONLY","effect_level":"READ_ONLY","environment":"LOCAL","resource_classes":["local_file"],"approval_required":false,"approval_present":false,"binding_requested":false,"validation_state":"NOT_REQUIRED","repository_action":false,"release_action":false,"dependency_state":{"mandatory_external_engine":false,"mandatory_hosted_service":false,"mandatory_package_manager":false,"mandatory_network":false,"mandatory_central_service":false},"taxonomy_binding_state":"TRANSLATED_OR_NOT_APPLICABLE","human_status_transfer_state":"NONE","claim_state":{},"evidence_state":{},"unknown_fields":[],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"material_transition":true,"tool_configured":true,"tool_available":true,"tool_authorized":false,"tool_invoked":false,"tool_endpoint":"LOCAL_CLI"}
  result.decision == "ALLOW"
}

test_q2_low_1_111 if {
  result := deterministic_policy.decision with input as {"policy_pack_id":"AIR_DETERMINISTIC_POLICY_PACK_V1","policy_pack_version":"1.1.0","policy_mode":"PROMPT_SIMULATED","policy_posture":"LOW","active_contract_id":"AIR_ACTIVE_CONTRACT_TEST_V1","active_step":"TEST","action_class":"READ_ONLY","effect_level":"READ_ONLY","environment":"LOCAL","resource_classes":["local_file"],"approval_required":false,"approval_present":false,"binding_requested":false,"validation_state":"NOT_REQUIRED","repository_action":false,"release_action":false,"dependency_state":{"mandatory_external_engine":false,"mandatory_hosted_service":false,"mandatory_package_manager":false,"mandatory_network":false,"mandatory_central_service":false},"taxonomy_binding_state":"TRANSLATED_OR_NOT_APPLICABLE","human_status_transfer_state":"NONE","claim_state":{},"evidence_state":{},"unknown_fields":[],"input_provenance":{"state":"FILE_BACKED_TEST_CASE"},"material_transition":true,"tool_configured":true,"tool_available":true,"tool_authorized":true,"tool_invoked":false,"tool_endpoint":"LOCAL_CLI"}
  result.decision == "ALLOW"
}
