from __future__ import annotations
from dataclasses import dataclass
from typing import Any, Protocol

ADAPTER_CONTRACT = "AIR_DURABLE_PROVENANCE_PROVIDER_ADAPTER_V1"
CANONICALIZATION_CONTRACT = "AIR_CANONICAL_JSON_SNAPSHOT_V1"

class ProviderIntegrityError(RuntimeError): pass
class ProviderGenerationMismatch(ProviderIntegrityError): pass

@dataclass(frozen=True)
class SnapshotKey:
    namespace_id: str
    emission_sequence: int
    ledger_entry_ref: str
    canonical_object_sha256: str

class DurableProvenanceProvider(Protocol):
    def describe_provider(self) -> dict[str, Any]: ...
    def probe_write_readback(self) -> dict[str, Any]: ...
    def open_project_namespace(self, namespace_id: str) -> dict[str, Any]: ...
    def prepare_snapshot(self, key: SnapshotKey, canonical_object_snapshot: Any) -> dict[str, Any]: ...
    def read_snapshot(self, key: SnapshotKey) -> dict[str, Any]: ...
    def commit_visible(self, key: SnapshotKey) -> dict[str, Any]: ...
    def mark_orphaned(self, key: SnapshotKey) -> dict[str, Any]: ...
    def retrieve_committed_range(self, namespace_id: str, start: int, end: int) -> list[dict[str, Any]]: ...
    def verify_coverage(self, namespace_id: str, expected: list[dict[str, Any]]) -> dict[str, Any]: ...
